<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Taggable')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
//                                      ->prependFile($this->basePath() . '/js/tiny_mce/jquery.tinymce.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
    ?>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav pull-left">
              <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
            </ul>
            <ul class="nav pull-right">

              <li><a href="<? echo $this->url('taggable/default', array('controller' => 'taggable', 'action' => 'index')); ?>"><?php echo $this->translate('Taggables') ?></a></li>
              <li><a href="<? echo $this->url('taggable/default', array('controller' => 'tag', 'action' => 'index')); ?>"><?php echo $this->translate('Tags') ?></a></li>

            </ul>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>
    <div class="container">
        <?php if (count($messages)) : ?>
          <ul class="flash-messages unstyled">
              <?php foreach ($messages as $message) : ?>
                <li>
                    <?php
                    $ztba = $this->ztbAlert();
                    $m = $message->message;
                    echo ($message->error) ? $ztba->error($m) : $ztba->success($m);
                    ?>
                </li>
            <?php endforeach; ?>
          </ul>
      <?php endif ?>
      <?php echo $this->content; ?>
      <hr>
      <footer>
        <p class="pull-left">
        </p>
        <p class="pull-right">
        </p>
      </footer>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
  </body>
</html>
